version: "3"

services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    env_file:
      - .env
  web:
    build: .
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@gmail.com
      PGADMIN_DEFAULT_PASSWORD: d1j2r3c4
    depends_on:
      - db
  redis:
    image: redis:7.0.5-alpine
    hostname: redis
    command: ["redis-server", "--appendonly", "yes"]
    env_file:
      - .env
    ports:
      - '6379:6379'
  celery_worker:
    container_name: celery_worker
    build: .
    command: [ 'celery', '-A', 'src.celery_task.tasks', 'worker', '-l', 'info' ]
    volumes:
      - .:/app
    depends_on:
      - redis
      - web
  flower:
    container_name: flower
    build: .
    command: [ 'celery', '-A', 'src.celery_task.tasks', 'flower', '--port=5555']
    ports:
      - "5556:5555"
    depends_on:
      - web
      - redis
      - celery_worker
