"""Create groupaccess

Revision ID: 0a9c94d55ddd
Revises: 355a4296839e
Create Date: 2024-04-08 15:59:16.089169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a9c94d55ddd'
down_revision: Union[str, None] = '355a4296839e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_access',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('access', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group_tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('group_tasks', sa.Column('owner', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'group_tasks', 'user', ['owner'], ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'group_tasks', type_='foreignkey')
    op.drop_column('group_tasks', 'owner')
    op.drop_table('group_access')
    # ### end Alembic commands ###
