"""Add Role

Revision ID: 2fb5f6a8ac8d
Revises: 30b6f28ae19f
Create Date: 2024-04-15 13:15:29.497382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fb5f6a8ac8d'
down_revision: Union[str, None] = '30b6f28ae19f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
