"""Solve the problem with relation GroupAccess and User

Revision ID: 30b6f28ae19f
Revises: c57abf3682aa
Create Date: 2024-04-08 16:25:24.427406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30b6f28ae19f'
down_revision: Union[str, None] = 'c57abf3682aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
