"""Add role to Access

Revision ID: 3e5f567a505f
Revises: 2fb5f6a8ac8d
Create Date: 2024-04-15 13:23:59.374903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e5f567a505f'
down_revision: Union[str, None] = '2fb5f6a8ac8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_access', sa.Column('role', sa.Enum('admin', 'manager', 'user', name='role'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_access', 'role')
    # ### end Alembic commands ###
