"""Create Relationship

Revision ID: baf6fc03b50b
Revises: 0f5f642cbd39
Create Date: 2024-03-25 14:30:09.806783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baf6fc03b50b'
down_revision: Union[str, None] = '0f5f642cbd39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('task', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'group_tasks', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'group_id')
    op.drop_table('group_tasks')
    # ### end Alembic commands ###
