"""Solve the problem with relation 

Revision ID: c57abf3682aa
Revises: 0a9c94d55ddd
Create Date: 2024-04-08 16:23:16.820564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c57abf3682aa'
down_revision: Union[str, None] = '0a9c94d55ddd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
